import styles from "./page.module.css";

export const metadata = {
  title: "NextJS Supabase Auth",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <h1>Hello from Nextjs</h1>
    </main>
  );
}
