export const metadata = {
  title: "NextJS Supabase Auth | Error",
  description: "Generated by create next app",
};

export default function ErrorPage() {
  return <p>Sorry, something went wrong</p>;
}
